# -*- coding: utf-8 -*-
"""Keyword_Program.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16HgxgtvUPycgUN90vdh-u6ICTkxFi_Zh
"""

import pandas as pd
import numpy as np

df = pd.read_csv('C:/Users/kakaopaysec/Desktop/발표용 자료/test_slim.csv')



while True:

  keyword = input('키워드를 입력해주세요 : ')
  check = 0

  if keyword == 'stop':
    print('프로그램을 종료합니다.')
    break

  for i in df.index:

    info_list = df.loc[i,:].tolist()
    info_list2 = []
    try:
      temp = info_list.index(np.nan)
      info_list2 = info_list[:temp]
    except:
      info_list2 = info_list
    company = info_list2[0]

    try:
      matching = [s for s in info_list2 if keyword == s]


      if matching:
        print('관련 종목은 ' + info_list2[0] + ' 입니다.')
        check = 1

      if i == df.index[-1] and check == 0:
        print('등록된 키워드가 없습니다. 검색어를 다시 입력해주세요.')
      
    except Exception as e:
      # print("error : ", e)
      pass
    
    if i == df.index[-1]+1:
      break


